### PR TITLE
Feature/user information section/28

### LINKED ISSUE #28: User Profile Page
- [ ] (#26)
- [ ] (#27)

### PR DESCRIPTION
**Pull request by Yin-Lynn-Htun**
resolve #28 #27 #26

### CODE REVIEW

**Comment by JiahuiChen99** [comment]
I think this could have been something like the following. **User's cards** doesn't depend on **User profile information** so could've been developed at the same time.
<div align = "center">
User Profile Page
</div>

Note that since this is a branch derives from `loginAndRegisterLogic` it also contains those changes. Please create **feature branches** from `dev` branch.

<div align = "center">
Branch comparison
</div>

**Comment by Yin-Lynn-Htun** [comment]
So, will there be 3 branches in total, i.e, user profile page, user info section and user card section? I thought there will be only 2 branches and _the user info section_ always have to be at the top of _the card section_, so I decided to combine them in only one branch.

**Comment by JiahuiChen99** [comment]
Yup, you can develop those components separately and put them together in the parent branch 👍

**Review by JiahuiChen99 — APPROVED** [review]
Well done with the user profile! Keep in my what I told you in the first review for the future (You've done well for the #38 👍)
I'd suggest @mokumoku-lovers/moku-front to review this too 👀

**Pull request merged**
