### PR TITLE
Pages/register and login

### PR DESCRIPTION
**Pull request by Yin-Lynn-Htun**
#8 Added Login, Register Pages  and initial setup for redux and react router dom

### CODE REVIEW

**Review by JiahuiChen99 — CHANGES_REQUESTED** [review]
Changes must never be merged into **`main branch`**. Please change this PR to pages/registerAndLogin > dev.

@mokumoku-lovers/moku-front @mokumoku-lovers/moku-front

**Comment by Yin-Lynn-Htun** [comment]
> Changes must never be merged into **`main branch`** 🥺 . Please change this PR to `pages/registerAndLogin > dev`.
> 
> @mokumoku-lovers/moku-front @mokumoku-lovers/moku-front

Oops, my bad. I updated the base branch to dev. Thanks for letting me know.

**Comment by JiahuiChen99** [comment]
## Tips and good practices
Remember, for future work, that feature branches like this PR ~ Login and Register page should come from **`dev`**. At this moment,  **pages/registerAndLogin** branch is child of **main**.

✔️ Now the commits have commit types 👍 , but try to add **`:`** after it to differentiate it from the commit message
64205b0
64f82d5
d59dabb


Register Page and Login Page could be separated into different Stories even if they are very similar.
For the IntroSection maybe you could have created a new Issue (**Intro Section Component**). After that PR intro_section > RegisterPage
<div align = "center">

</div>

c0af1db could be a `chore`

For further information and examples of git commit best practices take a look in this post [Udacity Git Style Guide](https://udacity.github.io/git-styleguide/)
<div align = "center">

</div>

**Review by JiahuiChen99 — APPROVED** [review]

**Review by hatoriMain — CHANGES_REQUESTED** [review]
## Reviews from shin chan
### 1. client folder
I think the code inside the client folder should be moved outside since it made the structure over nested.
The structure could be much more clear like this:
mokumoku-frontend->src

### 2.Lack 'react-router-dom' dependency
image
The 'react-router-dom' should be added into package.json

### 3. Name mismatching
image
image

The file name of the 'login.module.css' and 'formButton.module.css' should be changed into 'Login.module.css' and 'FormButton.module.css'

### 4. Some advices about user experience
- In register page, Maybe password form can be added to check about if two passwords are matching.
- I think the size of all font in the register & login page could be much bigger.

This is my first review with jiahui's help(we co-reviewed this code).  
😊And Thank you so much for your contribution! The code itself all looks fine!

**Comment by JiahuiChen99** [comment]
Well done! 👍

**Review by NicoleChow08 — APPROVED** [review]

**Pull request merged**
